keys:
  - &users:
    - &aaron_dodd 'age1dklej440dm807874vp2lrz7m72094s2v27autrhs7u0vjpxe75csttf2e0'
  - &hosts:
    - &aetherius 'age1xakuvc5xsx07zrgqq02vtj488wcqf5z5966f72zjjxtv0r9jwfvqpw56yz'

creation_rules:
  - path_regex: secrets/hosts/aetherius/secrets(/[^/]+)?\.ya?ml$
    key_groups:
      - age:
        - *aaron_dodd
        - *aetherius

  - path_regex: secrets/hosts/vmware/secrets(/[^/]+)?\.ya?ml$
    key_groups:
      - age:
        - *aaron_dodd

