keys:
  - &users:
    - &aaron_dodd 'age1uey2wd2fqf46tnhjkn904mar4zdkfxt6n6tx8k9fp2du5ypqk92sjtv87p'
  - &hosts:
    - &aetherius 'age1l3kvyps4ltkpaz7ht6mmwaxwvc3gjm3ht0e9qdkl5dyszmv4g4rsumnu9x'

creation_rules:
  - path_regex: secrets/hosts/aetherius/secrets(/[^/]+)?\.ya?ml$
    key_groups:
      - age:
        - *aaron_dodd
        - *aetherius

  - path_regex: secrets/hosts/vmware/secrets(/[^/]+)?\.ya?ml$
    key_groups:
      - age:
        - *aaron_dodd

