name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  deadnix:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: astro/deadnix-action@v1

