name: Code Analysis

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check Code
        run: |
          nix fmt
          git diff --exit-code

