name: Flake Checker

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

