name: Flake Lock Updater

on:
  schedule:
    - cron: '0 6 * * SAT'
  workflow_dispatch:

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Update flake.lock
        id: flake-update
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "chore: update flake.lock"
          commit-msg: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automatic
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Automatically merge flake.lock update
        if: ${{ steps.flake-update.outputs.pull-request-operation }} == 'created'
        run: |
          gh pr merge ${{ steps.flake-update.outputs.pull-request-number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

