name: Flake Lock Updater

on:
  schedule:
    - cron: '0 12 * * 1,5'
  workflow_dispatch:

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automatic

