name: Nix Checker

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nix-checker:
    name: Nix Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nix
        run: |
          nix fmt
          git diff --exit-code

